const NETWORK="rinkeby"
const URL= null
const BLOCKSTART=0 
const RERUNTIME=180000
const GASPRICE=20000000000
const ERASE_DATABASE_ON_SYNC=false
const TIMEZONE = "America/Toronto"
const PRUNING = true
const EXCHANGE_ADDRESSES =  ["0x03cb1f9422E290C8bFD93D8FEBA5DE6bb90c53B6"]


module.exports = {
    NETWORK, 
    URL,
    BLOCKSTART, 
    RERUNTIME, 
    GASPRICE, 
    ERASE_DATABASE_ON_SYNC,
    TIMEZONE,
    PRUNING,
    EXCHANGE_ADDRESSES
}
